// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChmOOvjlfRhcE03WaIuADwO0BNQ92cKzQ',
    appId: '1:349045434201:web:a0ccb9236e3475e7fa0e48',
    messagingSenderId: '349045434201',
    projectId: 'first-project-ba60c',
    authDomain: 'first-project-ba60c.firebaseapp.com',
    storageBucket: 'first-project-ba60c.appspot.com',
    measurementId: 'G-235YB17MQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNYZz-4SiAiFhWSewHx5i-RxGskOo7vi4',
    appId: '1:349045434201:android:ef612355521a83e1fa0e48',
    messagingSenderId: '349045434201',
    projectId: 'first-project-ba60c',
    storageBucket: 'first-project-ba60c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAIiO2KDwcR_dYlCFLTQaMMnvRkk3qf_w',
    appId: '1:349045434201:ios:124094ac4c2fdebefa0e48',
    messagingSenderId: '349045434201',
    projectId: 'first-project-ba60c',
    storageBucket: 'first-project-ba60c.appspot.com',
    iosBundleId: 'com.example.firebaseThroughCli',
  );
}
